### ISSUE TITLE
Week 9 Video Review

### ISSUE THREAD

**Issue by nolanplatt** [alvinzhengq/AP-CSA-T1#33]
**Video Links and Scores**

- Nolan: [Video](https://drive.google.com/file/d/1YRtqb12Ci4ZF20fkg23U4TrPepGv0Hp8/view?usp=sharing)
    - TBD/6
    - Evidence of Commits: [Algorithm Minilab](https://github.com/alvinzhengq/AP-CSA-T1/commit/6b2ebd84fc217d90dd71a55de751c081e8de3954), [2D Array Lab](https://github.com/alvinzhengq/AP-CSA-T1/commit/7fb517443c6244de349da046a95c23c0c1ff1a39)
- Akshay: [Video](https://www.youtube.com/watch?v=6AKFXF9nbFM)
    - TBD/6
    - Evidence of Commits: [Help with ASCII Lab (1)](https://github.com/alvinzhengq/AP-CSA-T1/commit/d7ecb042d506bedd629a6845de013757a1b02231), [Help with ASCII Lab (2)](https://github.com/alvinzhengq/AP-CSA-T1/commit/d37dc1c959f59e6c7f56e88521d63460dbde5ea3), [Algorithm Extend Lab (Akshay) ](https://github.com/alvinzhengq/AP-CSA-T1/commit/61fa6523beb2d662c031f1de091b62b9699ad5b8)
- Alvin: [Video](https://drive.google.com/file/d/18FhDKCXsbLqEcnQB8nvpyHcLyvOBHLkR/view?usp=sharing)
    - TBD/6
    - Evidence of Commits: [RGB Backend](https://github.com/alvinzhengq/AP-CSA-T1/commit/adfefa9788875a71dcc8b2d6312d00647137d860), [Algorithms Lab](https://github.com/alvinzhengq/AP-CSA-T1/commit/7917d020ff79af38e70b7a64819479e4ad898d3e)
- Sami: [video](https://drive.google.com/file/d/1zuspry8AYbZBu7suD6tX81ozcw_U0vKj/view?usp=sharing)
    - TBD/6
    - Evidence of Commits: [ASCII Art Lab](https://github.com/SamiDeshatty/My_random_-test/blob/main/src/src/asciiart/ASCIIArt.java) [Algorithm Lab] (https://github.com/alvinzhengq/AP-CSA-T1/commit/2fcec7c44b2ac4312c121478bc6f3e76a7258d18)
- Prisha: [Video](https://drive.google.com/file/d/16zEj3R3TtdlRqGifpg_QUBvSg1oSC8ul/view?usp=sharing)
    - TBD/6
    - Evidence of Commits: [Frontend Music HTML Page](https://github.com/alvinzhengq/AP-CSA-T1/commit/e9402b2a85e2e280a1d4c7d69cb38361a00e05b2)

**Grades and feedback below**

**Comment by jm1021** [comment]
@Akshay-Rohatgi
1. Discussed lab of creating ASCII art.  Algorithm looked more efficient than most as he was doing thing in less steps (less for loops).  Demo looked great.   Two things to improve on a.) a better introduction b.) more discussion of Control and VIew and just hit on high points of code.  Too much mouse highlights and scrolling.
2.) Discussed Geometric sequence using Classes.  Nothing really stood out here, like 1st example.  Highlighted some reuse of attributes from parent.  Shared runtime.

In both situations, it seemed like we jumped into code.  Since this is formal presentation you should be looking for "Hook" or "Engagement", this was not provided.

5.2/6

Comments are just OK.  not real passion or energy that I could detect.

1.75/2

**Comment by jm1021** [comment]
@SamiDeshatty

Strong preparation and association with CB units as requested.   I saw simple examples and mini lab examples.   All of this was very clear and educational.   I have been giving 5.5/6 for this type of presentation. 

Improvements for me would be to see team PBL vs just mini Lab usage.  Also, in this presentation an example of association seen in CB might have been a little better than examples provided.  Though, this is very good work.

Regarding comments, not super strong probably would award 1.75/2, but  I am taking another .25 as I believe this came in late and one of the comments above indicated such.
